spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres  # Usa 'db' en lugar de 'localhost'
    username: supabase_admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        model: deepseek-r1:7b
#    vectorstore:
#      pgvector:
#      index-type: HNSW
#      distance-type: COSINE_DISTANCE
#      dimensions: 1536
#      batching-strategy: TOKEN_COUNT # Optional: Controls how documents are batched for embedding
#      max-document-batch-size: 10000 # Optional: Maximum number of documents per batch

  servlet:
    multipart:
      max-file-size: 120MB
      max-request-size: 120MB
  # Timeouts
  mvc:
    async:
      request-timeout: 300000

