CREATE TABLE IF NOT EXISTS expenses (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        amount VARCHAR(255),
    date DATE,
    description VARCHAR(255),
    category VARCHAR(255),
    user_id BIGINT
    );

INSERT INTO expenses (amount, date, description, category, user_id)
VALUES ('22.000', '2025-01-27', 'Gastos administrativos', 'servicios', 1),
       ('15.000', '2025-01-28', 'Compra supermercado', 'comida', 1),
       ('5.000', '2025-01-29', 'Transporte', 'transporte', 1);